version: '3.7'
services:
  frontend:
    image: bereckova
    container_name: "bereckova"
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        SENTRY_URL: $SENTRY_URL
        SENTRY_DSN: $SENTRY_DSN
        SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN