name: 'Pull request - created'

on:
  pull_request:
    branches:
      - master
      - stage

jobs:
  pull-request:
    runs-on: ubuntu-latest
    env:
      REGION: europe-west1
      PROJECT_NAME: studioart-prod
      SERVICE_NAME: bereckova
      DOCKER_IMG: eu.gcr.io/studioart-prod/bereckova:latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Build Docker image'
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          docker-compose build
          docker tag bereckova:latest ${{ env.DOCKER_IMG }}